$(document).ready(function(){

  // MODAL
  var modalText = {
    roambi: {
      title: 'Orahi',
      tag: 'School Bus Tracking',
      detail: 'Orahi provides live school bus tracking to parents and school administration. Using this site, school administration and orahi admins can monitor and control bus routes. This site provides various other features for the ease of administration.',
      link: 'https://myschool.orahi.com'
    },
    walker: {
      title: 'Ayursparsh Healthcare',
      tag: 'Ayurvedics',
      detail: 'Ayursparsh Healthcare offers ayurvedic consultations and medicines to patients. Where allopathy treats you for a short period, ayurveda claims to treat you from root. Site built on python helps the doctor connect with its patients and book various services offered by the clinic online.',
      link: 'https://ayursparshhealthcare.com'
    },
    mystand: {
      title: 'Singhania Chemicals',
      tag: 'Customer and Product Management',
      detail: 'Singhania chemicals is a leader in chemicals and metal distribution all across north India. Scale at which they operate, it was getting difficult for them to manage products and customers due to complex product/customer mapping. So to solve their problem I have built a webapp that simplifies and automates their task. Both admin and users can login and do their respective tasks.',
      link: 'https://devnitros.appspot.com/'
    },
    never: {
      title: 'Various applications of Neuroscience',
      tag: 'Internet of Things',
      detail: '<strong>Mind driven Quadcopter:</strong> Built a quadcopter that is driven by the power of mind. Used an EEG bio sensor to interface with Android device connected to realtime database. Data received from bio sensor is used to accelerate and decelerate the quadcopter. When a person concentrates the quadcopter accelarates and flies, and when the person relaxes his mind and thoughts, the quadcopter decelerates and  gets back to ground. <br> <strong>Music Shuffle:</strong> This application was also built on android. EEG biosenson also has the capability to detect blinks, so using making use of that I built a Music Application that shuffles or plays the next track in queue when user blinks intentionally.<br><strong>Brainwave Visualiser:</strong> Built on android, user can visualise his/her brain activity in realtime on a graph. These alpha, beta, gamma waves are generated by our brains due to the electrical activity in neurons. These waves are used to study different sleep disorders and various other neurological related problems.',
    },
    powur: {
      title: '108 Emergency',
      tag: 'Hackathon',
      detail: 'Participated in the All India 108 Hackathon organised by IIT Madras and TNHSP.<br><strong>Problem Statement:</strong> In India we have an emergency calling number that responds when a person is in a state of Medical, Fire, or Crime emergency. As soon as the call centre receives a call, it immediately dispatches an Ambulance or PCR. But it takes a lot of time for the relief to reach the victim. Hundreds and thousands of lives are lost due to the ambulance not reaching the victim in time. We were asked to build product that would cater to this problem.<br>' +
              '<strong>Solution:</strong> I built a client side application and call centre side application. The client simply lodges a request. All the relevant information gets sent to the call centre with the exact GPS Coordinates. The system also automates the process of dispatching an ambulance. All relevant information is sent using which the driver can easily navigate to the victims location. This made the whole process extremely fast and reliable.<br>' +
              '<strong>USP:</strong> The app works offline as well. There are areas with low internet connectivity, so to make app work offline I created a messaging server on android that interacts over SMS with the user.This made the whole system extremely robust.<br>' +
              '<strong>Technologies:</strong> Python, Webapp2, Java, Android, Firebase, Google App Engine, HTML, CSS, Javascript',
    },
    themall: {
      title: 'Shazam for Fruits',
      tag: 'Image Classification',
      detail: 'Built an image classifier using android and a django server. User clicks a photo of any fruit using android app, the image is then sent to the server. The server then classifies that image using tensorflow which is trained on thousands of fruit images. Result is given back to android application over HTTP.<br>' +
              'This app is an improved version of <strong>Jian Yang - Shazam for Food</strong> which only classified as Hot Dog or Not Hot Dog, I hope I can sell it for a million dollars ^_^',
    }
  };

  $('#gallery .cards').on('click', function(){
    // console.log(this);
    // console.dir(this);
    // console.log(this.id);
    fillModal(this.children[0].children[2].id);
    $('.modal-wrap').addClass('visible');
  });

  $('#gallery .button').on('click', function(){
    fillModal(this.id);
    $('.modal-wrap').addClass('visible');
  });

  $('.close').on('click', function(){
    $('.modal-wrap, #modal .button').removeClass('visible');
  });

  $('.mask').on('click', function(){
    $('.modal-wrap, #modal .button').removeClass('visible');
  });

  var carousel = $('#carousel'),
      slideWidth = 700,
      threshold = slideWidth/3,
      dragStart, 
      dragEnd;

  setDimensions();

  $('#next').click(function(){ shiftSlide(-1) })
  $('#prev').click(function(){ shiftSlide(1) })

  carousel.on('mousedown', function(){
    if (carousel.hasClass('transition')) return;
    dragStart = event.pageX;
    $(this).on('mousemove', function(){
      dragEnd = event.pageX;
      $(this).css('transform','translateX('+ dragPos() +'px)');
    });
    $(document).on('mouseup', function(){
      if (dragPos() > threshold) { return shiftSlide(1) }
      if (dragPos() < -threshold) { return shiftSlide(-1) }
      shiftSlide(0);
    });
  });

  function setDimensions() {
    if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
     slideWidth = $(window).innerWidth();
    }
    $('.carousel-wrap, .slide').css('width', slideWidth);
    $('.modal').css('max-width', slideWidth);
    $('#carousel').css('left', slideWidth * -1)
  }

  function dragPos() {
    return dragEnd - dragStart;
  }

  function shiftSlide(direction) {
    if (carousel.hasClass('transition')) return;
    dragEnd = dragStart;
    $(document).off('mouseup')
    carousel.off('mousemove')
            .addClass('transition')
            .css('transform','translateX(' + (direction * slideWidth) + 'px)'); 
    setTimeout(function(){
      if (direction === 1) {
        $('.slide:first').before($('.slide:last'));
      } else if (direction === -1) {
        $('.slide:last').after($('.slide:first'));
      }
      carousel.removeClass('transition')
      carousel.css('transform','translateX(0px)'); 
    },700)
  }

  function fillModal(id) {
    $('#modal .title').text(modalText[id].title);
    $('#modal .detail').html(modalText[id].detail);
    $('#modal .tag').text(modalText[id].tag);
    if (modalText[id].link) $('#modal .button').addClass('visible')
                                               .parent()
                                               .attr('href', modalText[id].link)

    $.each($('#modal li'), function(index, value ) {
      $(this).text(modalText[id].bullets[index]);
    });
    $.each($('#modal .slide'), function(index, value) {
      $(this).css({
        background: "url('img/slides/" + id + '-' + index + ".jpg') center center/cover",
        backgroundSize: 'cover'
      });
    });
  }
});
